openapi: "3.1.0"
info:
  version: "1.1"
  title: "Roomcloud Messaging API OpenApi definition"
  description: "To obtain a JWT token, use the Authentication API"
  x-last-updated: "2026-02-18"
servers:
  - url: "https://api.roomcloud.net"
    description: "Production"
  - url: "https://api-test-02.g.roomcloud.net"
    description: "Development server"

paths:
  /be/api/messaging/{account_id}:
    get:
      summary: read_test
      parameters:
        - name: account_id
          in: path
          required: true
          schema:
            type: string
        - name: date_from
          in: query
          required: false
          schema:
            type: string
            format: date-time
        - name: date_to
          in: query
          required: false
          schema:
            type: string
            format: date-time
        - name: conversation_id
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "./schemas/conversation.yaml#/MessagingSuccess"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "./schemas/commons.yaml#/ResponseError"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "./schemas/commons.yaml#/ResponseError"
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "./schemas/commons.yaml#/ResponseError"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "./schemas/commons.yaml#/ResponseError"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "./schemas/commons.yaml#/ResponseError"
      tags:
        - messaging
      security:
        - JWTAuth: []

components:
  securitySchemes:
    JWTAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
# Commons (Error, ErrorRS, Timestamp, Paging, Base Response Envelopes)
    Error:
      $ref: "./schemas/commons.yaml#/Error"

    Timestamp:
      $ref: "./schemas/commons.yaml#/Timestamp"

    OpenApiPaging:
      $ref: "./schemas/commons.yaml#/OpenApiPaging"

    OpenApiResponseSuccessBase:
      $ref: "./schemas/commons.yaml#/OpenApiResponseSuccessBase"

    ResponseError:
      $ref: "./schemas/commons.yaml#/ResponseError"

    # Messaging – Oggetti di dominio
    Conversation:
      $ref: "./schemas/conversation.yaml#/Conversation"

    ConversationList:
      $ref: "./schemas/conversation.yaml#/ConversationList"

    Message:
      $ref: "./schemas/conversation.yaml#/Message"

    Participant:
      $ref: "./schemas/conversation.yaml#/Participant"

    Attachment:
      $ref: "./schemas/conversation.yaml#/Attachment"

    Reservation:
      $ref: "./schemas/conversation.yaml#/Reservation"

    Unit:
      $ref: "./schemas/conversation.yaml#/Unit"